# Generated by Django 3.0.8 on 2021-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_auto_20210526_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='activi_comerciales',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
