# Generated by Django 3.0.8 on 2021-05-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0003_activi_comerciales_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='activi_comerciales',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
